# See https://aka.ms/yaml

pr: none
trigger:
  tags:
    include:
      - v*

resources:
  containers:
    - container: fedora
      image: ucfconsort.azurecr.io/ucx/fedora:1
      endpoint: ucfconsort_registry

stages:
  - stage: Release
    jobs:
      - job: release
        displayName: build tarball and source rpm
        container: fedora
        steps:
          - bash: ./autogen.sh
            displayName: Setup autotools

          - bash: |
              sed -i -e 's/@VERSION@-SNAPSHOT/@VERSION@/g' bindings/java/pom.xml.in
              sed -i -e 's/@VERSION@-SNAPSHOT/@VERSION@/g' bindings/java/src/main/native/Makefile.am
            displayName: Set JUCX release version

          - bash: |
              set -eE
              gcc --version
              ./contrib/configure-release --with-java
              ./contrib/buildrpm.sh -s -t -b
            displayName: Build tarball

          - bash: |
              set -eE
              gcc --version
              ./contrib/configure-release-mt --with-java
              make -j `nproc`
              tmp_settings=" bindings/java/src/main/native/build-java/tmp-settings.xml"
              echo "<settings><servers><server>" > $tmp_settings
              echo "<id>ossrh</id><username>${SONATYPE_USERNAME}</username>" >> $tmp_settings
              echo "<password>${SONATYPE_PASSWORD}</password>" >> $tmp_settings
              echo "</server></servers></settings>" >> $tmp_settings
              make -C bindings/java/src/main/native/ publish --settings $tmp_settings
            displayName: Make and publish JUCX release jar

          - task: GithubRelease@0
            displayName: Create/edit GitHub Draft Release
            inputs:
              githubConnection: release
              repositoryName: openucx/ucx
              action: edit
              tag: $(Build.SourceBranchName)
              isDraft: true
              addChangeLog: false
              assets: |
                ./ucx-*.tar.gz
                ./rpm-dist/ucx-*.src.rpm
