# See https://aka.ms/yaml

pr: none
trigger:
  tags:
    include:
      - v*

resources:
  containers:
    - container: fedora
      image: ucfconsort.azurecr.io/ucx/fedora:1
      endpoint: ucfconsort_registry

stages:
  - stage: Release
    jobs:
      - job: release
        displayName: build tarball and source rpm
        container: fedora
        steps:
          - template: jucx-publish.yml
            parameters:
              target: publish

          - task: GithubRelease@0
            displayName: Create/edit GitHub Draft Release
            inputs:
              githubConnection: release
              repositoryName: openucx/ucx
              action: edit
              tag: $(Build.SourceBranchName)
              isDraft: true
              addChangeLog: false
              assets: |
                ./ucx-*.tar.gz
                ./rpm-dist/ucx-*.src.rpm
